name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 10
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: build
  steps:
        - uses: actions/checkout@v3
          with:
            path: build
        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        - name: Install dependencies
          run: npm ci
        - name: Build code
          run: npm run build
        - name: Cleanup
          if: always()
          run: |
            pwd
            cd .. && rm -rf ./build